In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [2]:
dataset = pd.read_csv('train.csv')
dataset2 = pd.read_csv('test.csv')

In [3]:
dataset.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores     ...       px_height  px_width   ram  sc_h  sc_w  \
0        188        2     ...              20       756  2549     9     7   
1        136        3     ...             905      1988  2631    17     3   
2        145        5     ...            1263      1716  2603    11     2   
3        131        6     ...            1216      1786  2769    16     8   
4        141        2     ...            1208      1212  1411     8     2   

   talk_time  three_g  touch_screen  wifi  price_range  
0         19        0             0     1            1  
1          7        1             1     0            2  
2          9        1             1     0            2  
3         11        1             0     0            2  
4         15        1             1     0            1  

[5 rows x 21 columns]

In [4]:
dataset2.drop(columns=['id'],inplace=True)
dataset2.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0           1043     1          1.8         1  14       0           5    0.1   
1            841     1          0.5         1   4       1          61    0.8   
2           1807     1          2.8         0   1       0          27    0.9   
3           1546     0          0.5         1  18       1          25    0.5   
4           1434     0          1.4         0  11       1          49    0.5   

   mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        193        3  16        226      1412  3476    12     7          2   
1        191        5  12        746       857  3895     6     0          7   
2        186        3   4       1270      1366  2396    17    10         10   
3         96        8  20        295      1752  3893    10     0          7   
4        108        6  18        749       810  1773    15     8          7   

   three_g  touch_screen  wifi  
0        0             1     0  
1        1             0     0  
2        0             1     1  
3        1             1     0  
4        1             0     1

In [5]:
#dataset = dataset.drop(columns='clock_speed')
#dataset = dataset.drop(columns='m_dep')

In [6]:
for i in enumerate(dataset.columns):
    print(i)

(0, 'battery_power')
(1, 'blue')
(2, 'clock_speed')
(3, 'dual_sim')
(4, 'fc')
(5, 'four_g')
(6, 'int_memory')
(7, 'm_dep')
(8, 'mobile_wt')
(9, 'n_cores')
(10, 'pc')
(11, 'px_height')
(12, 'px_width')
(13, 'ram')
(14, 'sc_h')
(15, 'sc_w')
(16, 'talk_time')
(17, 'three_g')
(18, 'touch_screen')
(19, 'wifi')
(20, 'price_range')


In [7]:
for i in enumerate(dataset2.columns):
    print(i)

(0, 'battery_power')
(1, 'blue')
(2, 'clock_speed')
(3, 'dual_sim')
(4, 'fc')
(5, 'four_g')
(6, 'int_memory')
(7, 'm_dep')
(8, 'mobile_wt')
(9, 'n_cores')
(10, 'pc')
(11, 'px_height')
(12, 'px_width')
(13, 'ram')
(14, 'sc_h')
(15, 'sc_w')
(16, 'talk_time')
(17, 'three_g')
(18, 'touch_screen')
(19, 'wifi')


In [8]:
dataset.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores     ...       px_height  px_width   ram  sc_h  sc_w  \
0        188        2     ...              20       756  2549     9     7   
1        136        3     ...             905      1988  2631    17     3   
2        145        5     ...            1263      1716  2603    11     2   
3        131        6     ...            1216      1786  2769    16     8   
4        141        2     ...            1208      1212  1411     8     2   

   talk_time  three_g  touch_screen  wifi  price_range  
0         19        0             0     1            1  
1          7        1             1     0            2  
2          9        1             1     0            2  
3         11        1             0     0            2  
4         15        1             1     0            1  

[5 rows x 21 columns]

In [9]:
dataset['clock_speed'] = dataset['clock_speed'].astype(str)
dataset['m_dep'] = dataset['m_dep'].astype(str)
dataset2['clock_speed'] = dataset2['clock_speed'].astype(str)
dataset2['m_dep'] = dataset2['m_dep'].astype(str)

In [10]:
labelenc = LabelEncoder()

In [11]:
labelenc.fit(dataset['clock_speed'])

LabelEncoder()

In [12]:
dataset['clock_speed'] = labelenc.transform(dataset['clock_speed'])
dataset2['clock_speed'] = labelenc.transform(dataset2['clock_speed'])

In [13]:
dataset.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory m_dep  \
0            842     0           17         0   1       0           7   0.6   
1           1021     1            0         1   0       1          53   0.7   
2            563     1            0         1   2       1          41   0.9   
3            615     1           20         0   0       0          10   0.8   
4           1821     1            7         0  13       1          44   0.6   

   mobile_wt  n_cores     ...       px_height  px_width   ram  sc_h  sc_w  \
0        188        2     ...              20       756  2549     9     7   
1        136        3     ...             905      1988  2631    17     3   
2        145        5     ...            1263      1716  2603    11     2   
3        131        6     ...            1216      1786  2769    16     8   
4        141        2     ...            1208      1212  1411     8     2   

   talk_time  three_g  touch_screen  wifi  price_range  
0         19        0             0     1            1  
1          7        1             1     0            2  
2          9        1             1     0            2  
3         11        1             0     0            2  
4         15        1             1     0            1  

[5 rows x 21 columns]

In [14]:
dataset2.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory m_dep  \
0           1043     1           13         1  14       0           5   0.1   
1            841     1            0         1   4       1          61   0.8   
2           1807     1           23         0   1       0          27   0.9   
3           1546     0            0         1  18       1          25   0.5   
4           1434     0            9         0  11       1          49   0.5   

   mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        193        3  16        226      1412  3476    12     7          2   
1        191        5  12        746       857  3895     6     0          7   
2        186        3   4       1270      1366  2396    17    10         10   
3         96        8  20        295      1752  3893    10     0          7   
4        108        6  18        749       810  1773    15     8          7   

   three_g  touch_screen  wifi  
0        0             1     0  
1        1             0     0  
2        0             1     1  
3        1             1     0  
4        1             0     1

In [15]:
onehotencoder = OneHotEncoder(categorical_features=[2])

In [16]:
df = pd.DataFrame(onehotencoder.fit_transform(dataset).toarray())
df2 = pd.DataFrame(onehotencoder.fit_transform(dataset2).toarray())

In [17]:
df.head(10)

0    1    2    3    4    5    6    7    8    9  ...       36      37  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...     20.0   756.0   
1  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    905.0  1988.0   
2  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1263.0  1716.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1216.0  1786.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0 ...   1208.0  1212.0   
5  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1004.0  1654.0   
6  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    381.0  1018.0   
7  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    512.0  1149.0   
8  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    386.0   836.0   
9  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1137.0  1224.0   

       38    39    40    41   42   43   44   45  
0  2549.0   9.0   7.0  19.0  0.0  0.0  1.0  1.0  
1  2631.0  17.0   3.0   7.0  1.0  1.0  0.0  2.0  
2  2603.0  11.0   2.0   9.0  1.0  1.0  0.0  2.0  
3  2769.0  16.0   8.0  11.0  1.0  0.0  0.0  2.0  
4  1411.0   8.0   2.0  15.0  1.0  1.0  0.0  1.0  
5  1067.0  17.0   1.0  10.0  1.0  0.0  0.0  1.0  
6  3220.0  13.0   8.0  18.0  1.0  0.0  1.0  3.0  
7   700.0  16.0   3.0   5.0  1.0  1.0  1.0  0.0  
8  1099.0  17.0   1.0  20.0  1.0  0.0  0.0  0.0  
9   513.0  19.0  10.0  12.0  1.0  0.0  0.0  0.0  

[10 rows x 46 columns]

In [18]:
df2.head()

0    1    2    3    4    5    6    7    8    9  ...     35      36  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   16.0   226.0   
1  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   12.0   746.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    4.0  1270.0   
3  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   20.0   295.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0 ...   18.0   749.0   

       37      38    39    40    41   42   43   44  
0  1412.0  3476.0  12.0   7.0   2.0  0.0  1.0  0.0  
1   857.0  3895.0   6.0   0.0   7.0  1.0  0.0  0.0  
2  1366.0  2396.0  17.0  10.0  10.0  0.0  1.0  1.0  
3  1752.0  3893.0  10.0   0.0   7.0  1.0  1.0  0.0  
4   810.0  1773.0  15.0   8.0   7.0  1.0  0.0  1.0  

[5 rows x 45 columns]

In [19]:
df = df.iloc[:, 1:]
df2 = df2.iloc[:, 1:]

In [20]:
df.iloc[:,[28]].head()

29
0   1.0
1   0.0
2   2.0
3   0.0
4  13.0

In [21]:
df2.iloc[:,[28]].head()

29
0  14.0
1   4.0
2   1.0
3  18.0
4  11.0

In [22]:
onehotencoder = OneHotEncoder(categorical_features=[28])

In [23]:
df = pd.DataFrame(onehotencoder.fit_transform(df).toarray())
df2 = pd.DataFrame(onehotencoder.fit_transform(df2).toarray())

In [24]:
df = df.iloc[:, 1:]
df2 = df2.iloc[:, 1:]

In [25]:
df.head()

1    2    3    4    5    6    7    8    9    10 ...       54      55  \
0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...     20.0   756.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    905.0  1988.0   
2  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1263.0  1716.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1216.0  1786.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1208.0  1212.0   

       56    57   58    59   60   61   62   63  
0  2549.0   9.0  7.0  19.0  0.0  0.0  1.0  1.0  
1  2631.0  17.0  3.0   7.0  1.0  1.0  0.0  2.0  
2  2603.0  11.0  2.0   9.0  1.0  1.0  0.0  2.0  
3  2769.0  16.0  8.0  11.0  1.0  0.0  0.0  2.0  
4  1411.0   8.0  2.0  15.0  1.0  1.0  0.0  1.0  

[5 rows x 63 columns]

In [26]:
df2.head()

1    2    3    4    5    6    7    8    9    10 ...     53      54  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   16.0   226.0   
1  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   12.0   746.0   
2  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    4.0  1270.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   20.0   295.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   18.0   749.0   

       55      56    57    58    59   60   61   62  
0  1412.0  3476.0  12.0   7.0   2.0  0.0  1.0  0.0  
1   857.0  3895.0   6.0   0.0   7.0  1.0  0.0  0.0  
2  1366.0  2396.0  17.0  10.0  10.0  0.0  1.0  1.0  
3  1752.0  3893.0  10.0   0.0   7.0  1.0  1.0  0.0  
4   810.0  1773.0  15.0   8.0   7.0  1.0  0.0  1.0  

[5 rows x 62 columns]

In [27]:
df.iloc[:,[48]].head()

49
0   7.0
1  53.0
2  41.0
3  10.0
4  44.0

In [28]:
df2.iloc[:,[48]].head()

49
0   5.0
1  61.0
2  27.0
3  25.0
4  49.0

In [29]:
onehotencoder = OneHotEncoder(categorical_features=[48])

In [30]:
df = pd.DataFrame(onehotencoder.fit_transform(df).toarray())
df2 = pd.DataFrame(onehotencoder.fit_transform(df2).toarray())

In [31]:
df = df.iloc[:, 1:]
df2 = df2.iloc[:, 1:]

In [32]:
df.head()

1    2    3    4    5    6    7    8    9    10  ...      115     116  \
0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0 ...     20.0   756.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    905.0  1988.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1263.0  1716.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0 ...   1216.0  1786.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1208.0  1212.0   

      117   118  119   120  121  122  123  124  
0  2549.0   9.0  7.0  19.0  0.0  0.0  1.0  1.0  
1  2631.0  17.0  3.0   7.0  1.0  1.0  0.0  2.0  
2  2603.0  11.0  2.0   9.0  1.0  1.0  0.0  2.0  
3  2769.0  16.0  8.0  11.0  1.0  0.0  0.0  2.0  
4  1411.0   8.0  2.0  15.0  1.0  1.0  0.0  1.0  

[5 rows x 124 columns]

In [33]:
df2.head()

1    2    3    4    5    6    7    8    9    10  ...    114     115  \
0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   16.0   226.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   12.0   746.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    4.0  1270.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   20.0   295.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   18.0   749.0   

      116     117   118   119   120  121  122  123  
0  1412.0  3476.0  12.0   7.0   2.0  0.0  1.0  0.0  
1   857.0  3895.0   6.0   0.0   7.0  1.0  0.0  0.0  
2  1366.0  2396.0  17.0  10.0  10.0  0.0  1.0  1.0  
3  1752.0  3893.0  10.0   0.0   7.0  1.0  1.0  0.0  
4   810.0  1773.0  15.0   8.0   7.0  1.0  0.0  1.0  

[5 rows x 123 columns]

In [34]:
df.iloc[:,[110]].head()

111
0  0.6
1  0.7
2  0.9
3  0.8
4  0.6

In [35]:
df2.iloc[:,[110]].head()

111
0  0.1
1  0.8
2  0.9
3  0.5
4  0.5

In [36]:
labelenc2 = LabelEncoder()

In [37]:
df.iloc[:,110] = labelenc2.fit_transform(df.iloc[:,110])
df2.iloc[:,110] = labelenc2.fit_transform(df2.iloc[:,110])

In [38]:
df.iloc[:,110].head()

0    5
1    6
2    8
3    7
4    5
Name: 111, dtype: int64

In [39]:
df2.iloc[:,110].head()

0    0
1    7
2    8
3    4
4    4
Name: 111, dtype: int64

In [40]:
onehotencoder = OneHotEncoder(categorical_features=[110])

In [143]:
df = pd.DataFrame(onehotencoder.fit_transform(df).toarray())
df2 = pd.DataFrame(onehotencoder.fit_transform(df2).toarray())

In [144]:
df = df.iloc[:, 1:]
df2 = df2.iloc[:, 1:]

In [145]:
df.head()

1    2    3    4    5    6    7    8    9    10  ...      123     124  \
0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0 ...     20.0   756.0   
1  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0 ...    905.0  1988.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0 ...   1263.0  1716.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0 ...   1216.0  1786.0   
4  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0 ...   1208.0  1212.0   

      125   126  127   128  129  130  131  132  
0  2549.0   9.0  7.0  19.0  0.0  0.0  1.0  1.0  
1  2631.0  17.0  3.0   7.0  1.0  1.0  0.0  2.0  
2  2603.0  11.0  2.0   9.0  1.0  1.0  0.0  2.0  
3  2769.0  16.0  8.0  11.0  1.0  0.0  0.0  2.0  
4  1411.0   8.0  2.0  15.0  1.0  1.0  0.0  1.0  

[5 rows x 132 columns]

In [146]:
df2.head()

1    2    3    4    5    6    7    8    9    10  ...    122     123  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   16.0   226.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0 ...   12.0   746.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0 ...    4.0  1270.0   
3  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   20.0   295.0   
4  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   18.0   749.0   

      124     125   126   127   128  129  130  131  
0  1412.0  3476.0  12.0   7.0   2.0  0.0  1.0  0.0  
1   857.0  3895.0   6.0   0.0   7.0  1.0  0.0  0.0  
2  1366.0  2396.0  17.0  10.0  10.0  0.0  1.0  1.0  
3  1752.0  3893.0  10.0   0.0   7.0  1.0  1.0  0.0  
4   810.0  1773.0  15.0   8.0   7.0  1.0  0.0  1.0  

[5 rows x 131 columns]

In [147]:
df.iloc[:, [119]].head()

120
0  188.0
1  136.0
2  145.0
3  131.0
4  141.0

In [148]:
df2.iloc[:, [119]].head()

120
0  193.0
1  191.0
2  186.0
3   96.0
4  108.0

In [149]:
onehotencoder = OneHotEncoder(categorical_features=[119])

In [150]:
df = pd.DataFrame(onehotencoder.fit_transform(df).toarray())
df2 = pd.DataFrame(onehotencoder.fit_transform(df2).toarray())

In [151]:
df = df.iloc[:, 1:]
df2 = df2.iloc[:, 1:]

In [152]:
df.head()

1    2    3    4    5    6    7    8    9    10  ...      242     243  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...     20.0   756.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    905.0  1988.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1263.0  1716.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1216.0  1786.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1208.0  1212.0   

      244   245  246   247  248  249  250  251  
0  2549.0   9.0  7.0  19.0  0.0  0.0  1.0  1.0  
1  2631.0  17.0  3.0   7.0  1.0  1.0  0.0  2.0  
2  2603.0  11.0  2.0   9.0  1.0  1.0  0.0  2.0  
3  2769.0  16.0  8.0  11.0  1.0  0.0  0.0  2.0  
4  1411.0   8.0  2.0  15.0  1.0  1.0  0.0  1.0  

[5 rows x 251 columns]

In [153]:
df2.head()

1    2    3    4    5    6    7    8    9    10  ...    241     242  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   16.0   226.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   12.0   746.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    4.0  1270.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   20.0   295.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   18.0   749.0   

      243     244   245   246   247  248  249  250  
0  1412.0  3476.0  12.0   7.0   2.0  0.0  1.0  0.0  
1   857.0  3895.0   6.0   0.0   7.0  1.0  0.0  0.0  
2  1366.0  2396.0  17.0  10.0  10.0  0.0  1.0  1.0  
3  1752.0  3893.0  10.0   0.0   7.0  1.0  1.0  0.0  
4   810.0  1773.0  15.0   8.0   7.0  1.0  0.0  1.0  

[5 rows x 250 columns]

In [154]:
df.iloc[:,[239]].head()

240
0  2.0
1  3.0
2  5.0
3  6.0
4  2.0

In [155]:
df2.iloc[:,[239]].head()

240
0  3.0
1  5.0
2  3.0
3  8.0
4  6.0

In [156]:
onehotencoder = OneHotEncoder(categorical_features=[239])

In [157]:
df = pd.DataFrame(onehotencoder.fit_transform(df).toarray())
df2 = pd.DataFrame(onehotencoder.fit_transform(df2).toarray())

In [158]:
df = df.iloc[:, 1:]
df2 = df2.iloc[:, 1:]

In [159]:
df.head()

1    2    3    4    5    6    7    8    9    10  ...      248     249  \
0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...     20.0   756.0   
1  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    905.0  1988.0   
2  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1263.0  1716.0   
3  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0 ...   1216.0  1786.0   
4  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1208.0  1212.0   

      250   251  252   253  254  255  256  257  
0  2549.0   9.0  7.0  19.0  0.0  0.0  1.0  1.0  
1  2631.0  17.0  3.0   7.0  1.0  1.0  0.0  2.0  
2  2603.0  11.0  2.0   9.0  1.0  1.0  0.0  2.0  
3  2769.0  16.0  8.0  11.0  1.0  0.0  0.0  2.0  
4  1411.0   8.0  2.0  15.0  1.0  1.0  0.0  1.0  

[5 rows x 257 columns]

In [160]:
df2.head()

1    2    3    4    5    6    7    8    9    10  ...    247     248  \
0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   16.0   226.0   
1  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   12.0   746.0   
2  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    4.0  1270.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0 ...   20.0   295.0   
4  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0 ...   18.0   749.0   

      249     250   251   252   253  254  255  256  
0  1412.0  3476.0  12.0   7.0   2.0  0.0  1.0  0.0  
1   857.0  3895.0   6.0   0.0   7.0  1.0  0.0  0.0  
2  1366.0  2396.0  17.0  10.0  10.0  0.0  1.0  1.0  
3  1752.0  3893.0  10.0   0.0   7.0  1.0  1.0  0.0  
4   810.0  1773.0  15.0   8.0   7.0  1.0  0.0  1.0  

[5 rows x 256 columns]

In [161]:
df.iloc[:, [246]].head()

247
0   2.0
1   6.0
2   6.0
3   9.0
4  14.0

In [162]:
df2.iloc[:, [246]].head()

247
0  16.0
1  12.0
2   4.0
3  20.0
4  18.0

In [163]:
dataset2['pc'].head()

0    16
1    12
2     4
3    20
4    18
Name: pc, dtype: int64

In [164]:
onehotencoder = OneHotEncoder(categorical_features=[246])

In [165]:
df = pd.DataFrame(onehotencoder.fit_transform(df).toarray())
df2 = pd.DataFrame(onehotencoder.fit_transform(df2).toarray())

In [166]:
df = df.iloc[:, 1:]
df2 = df2.iloc[:, 1:]

In [167]:
df.head()

1    2    3    4    5    6    7    8    9    10  ...      267     268  \
0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...     20.0   756.0   
1  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0 ...    905.0  1988.0   
2  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0 ...   1263.0  1716.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0 ...   1216.0  1786.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1208.0  1212.0   

      269   270  271   272  273  274  275  276  
0  2549.0   9.0  7.0  19.0  0.0  0.0  1.0  1.0  
1  2631.0  17.0  3.0   7.0  1.0  1.0  0.0  2.0  
2  2603.0  11.0  2.0   9.0  1.0  1.0  0.0  2.0  
3  2769.0  16.0  8.0  11.0  1.0  0.0  0.0  2.0  
4  1411.0   8.0  2.0  15.0  1.0  1.0  0.0  1.0  

[5 rows x 276 columns]

In [168]:
df2.head()

1    2    3    4    5    6    7    8    9    10  ...   266     267     268  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0   226.0  1412.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0   746.0   857.0   
2  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  1270.0  1366.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0   295.0  1752.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0   749.0   810.0   

      269   270   271   272  273  274  275  
0  3476.0  12.0   7.0   2.0  0.0  1.0  0.0  
1  3895.0   6.0   0.0   7.0  1.0  0.0  0.0  
2  2396.0  17.0  10.0  10.0  0.0  1.0  1.0  
3  3893.0  10.0   0.0   7.0  1.0  1.0  0.0  
4  1773.0  15.0   8.0   7.0  1.0  0.0  1.0  

[5 rows x 275 columns]

In [169]:
df.iloc[:, [269]].head()

270
0   9.0
1  17.0
2  11.0
3  16.0
4   8.0

In [170]:
df2.iloc[:, [269]].head()

270
0  12.0
1   6.0
2  17.0
3  10.0
4  15.0

In [171]:
onehotencoder = OneHotEncoder(categorical_features=[269])

In [172]:
df = pd.DataFrame(onehotencoder.fit_transform(df).toarray())
df2 = pd.DataFrame(onehotencoder.fit_transform(df2).toarray())

In [173]:
df = df.iloc[:, 1:]
df2 = df2.iloc[:, 1:]

In [174]:
df.head()

1    2    3    4    5    6    7    8    9    10  ...   280     281     282  \
0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0    20.0   756.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0   905.0  1988.0   
2  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0 ...   1.0  1263.0  1716.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  1216.0  1786.0   
4  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  1208.0  1212.0   

      283  284   285  286  287  288  289  
0  2549.0  7.0  19.0  0.0  0.0  1.0  1.0  
1  2631.0  3.0   7.0  1.0  1.0  0.0  2.0  
2  2603.0  2.0   9.0  1.0  1.0  0.0  2.0  
3  2769.0  8.0  11.0  1.0  0.0  0.0  2.0  
4  1411.0  2.0  15.0  1.0  1.0  0.0  1.0  

[5 rows x 289 columns]

In [175]:
df2.head()

1    2    3    4    5    6    7    8    9    10  ...   279  280     281  \
0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0 ...   1.0  0.0   226.0   
1  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  1.0   746.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  1270.0   
3  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  1.0   295.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0 ...   0.0  1.0   749.0   

      282     283   284   285  286  287  288  
0  1412.0  3476.0   7.0   2.0  0.0  1.0  0.0  
1   857.0  3895.0   0.0   7.0  1.0  0.0  0.0  
2  1366.0  2396.0  10.0  10.0  0.0  1.0  1.0  
3  1752.0  3893.0   0.0   7.0  1.0  1.0  0.0  
4   810.0  1773.0   8.0   7.0  1.0  0.0  1.0  

[5 rows x 288 columns]

In [176]:
df.iloc[:,283].head()

0    7.0
1    3.0
2    2.0
3    8.0
4    2.0
Name: 284, dtype: float64

In [177]:
df2.iloc[:,283].head()

0     7.0
1     0.0
2    10.0
3     0.0
4     8.0
Name: 284, dtype: float64

In [178]:
onehotencoder = OneHotEncoder(categorical_features=[283])

In [179]:
df = pd.DataFrame(onehotencoder.fit_transform(df).toarray())
df2 = pd.DataFrame(onehotencoder.fit_transform(df2).toarray())

In [180]:
df = df.iloc[:, 1:]
df2 = df2.iloc[:, 1:]

In [181]:
df.head()

1    2    3    4    5    6    7    8    9    10  ...   297  298     299  \
0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0 ...   0.0  0.0    20.0   
1  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  1.0   905.0   
2  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  1.0  1263.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0 ...   0.0  0.0  1216.0   
4  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  1.0  1208.0   

      300     301   302  303  304  305  306  
0   756.0  2549.0  19.0  0.0  0.0  1.0  1.0  
1  1988.0  2631.0   7.0  1.0  1.0  0.0  2.0  
2  1716.0  2603.0   9.0  1.0  1.0  0.0  2.0  
3  1786.0  2769.0  11.0  1.0  0.0  0.0  2.0  
4  1212.0  1411.0  15.0  1.0  1.0  0.0  1.0  

[5 rows x 306 columns]

In [182]:
df2.head()

1    2    3    4    5    6    7    8    9    10  ...   296  297  298  \
0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0 ...   1.0  1.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  1.0  1.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0 ...   1.0  0.0  0.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  1.0  1.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0 ...   0.0  0.0  1.0   

      299     300     301   302  303  304  305  
0   226.0  1412.0  3476.0   2.0  0.0  1.0  0.0  
1   746.0   857.0  3895.0   7.0  1.0  0.0  0.0  
2  1270.0  1366.0  2396.0  10.0  0.0  1.0  1.0  
3   295.0  1752.0  3893.0   7.0  1.0  1.0  0.0  
4   749.0   810.0  1773.0   7.0  1.0  0.0  1.0  

[5 rows x 305 columns]

In [183]:
df.iloc[:, 301].head()

0    19.0
1     7.0
2     9.0
3    11.0
4    15.0
Name: 302, dtype: float64

In [184]:
df2.iloc[:, 301].head()

0     2.0
1     7.0
2    10.0
3     7.0
4     7.0
Name: 302, dtype: float64

In [185]:
onehotencoder = OneHotEncoder(categorical_features=[301])

In [186]:
df = pd.DataFrame(onehotencoder.fit_transform(df).toarray())
df2 = pd.DataFrame(onehotencoder.fit_transform(df2).toarray())

In [187]:
df = df.iloc[:, 1:]
df2 = df2.iloc[:, 1:]

In [188]:
df.head()

1    2    3    4    5    6    7    8    9    10  ...   314  315  316  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  1.0  1.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0 ...   1.0  1.0  1.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0 ...   1.0  0.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  0.0  1.0   

      317     318     319  320  321  322  323  
0    20.0   756.0  2549.0  0.0  0.0  1.0  1.0  
1   905.0  1988.0  2631.0  1.0  1.0  0.0  2.0  
2  1263.0  1716.0  2603.0  1.0  1.0  0.0  2.0  
3  1216.0  1786.0  2769.0  1.0  0.0  0.0  2.0  
4  1208.0  1212.0  1411.0  1.0  1.0  0.0  1.0  

[5 rows x 323 columns]

In [189]:
df2.head()

1    2    3    4    5    6    7    8    9    10  ...      313  314  315  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1043.0  1.0  1.0   
1  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0 ...    841.0  1.0  1.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0 ...   1807.0  1.0  0.0   
3  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0 ...   1546.0  0.0  1.0   
4  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0 ...   1434.0  0.0  0.0   

   316     317     318     319  320  321  322  
0  0.0   226.0  1412.0  3476.0  0.0  1.0  0.0  
1  1.0   746.0   857.0  3895.0  1.0  0.0  0.0  
2  0.0  1270.0  1366.0  2396.0  0.0  1.0  1.0  
3  1.0   295.0  1752.0  3893.0  1.0  1.0  0.0  
4  1.0   749.0   810.0  1773.0  1.0  0.0  1.0  

[5 rows x 322 columns]

In [190]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [191]:
X.head()

1    2    3    4    5    6    7    8    9    10  ...      313  314  315  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    842.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0 ...   1021.0  1.0  1.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0 ...    563.0  1.0  1.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0 ...    615.0  1.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1821.0  1.0  0.0   

   316     317     318     319  320  321  322  
0  0.0    20.0   756.0  2549.0  0.0  0.0  1.0  
1  1.0   905.0  1988.0  2631.0  1.0  1.0  0.0  
2  1.0  1263.0  1716.0  2603.0  1.0  1.0  0.0  
3  0.0  1216.0  1786.0  2769.0  1.0  0.0  0.0  
4  1.0  1208.0  1212.0  1411.0  1.0  1.0  0.0  

[5 rows x 322 columns]

In [192]:
y.head()

0    1.0
1    2.0
2    2.0
3    2.0
4    1.0
Name: 323, dtype: float64

In [193]:
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
import tensorflow as tf
from tensorflow import keras as keras
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [194]:
#classifier = XGBClassifier()
#classifier = DecisionTreeClassifier()
#classifier = RandomForestClassifier()
#classifier = LogisticRegression()
#model = keras.models.Sequential()
#classifier = SVC()
classifier = KNeighborsClassifier()

In [93]:
model.add(tf.keras.layers.Dense(288, activation=tf.nn.relu))

model.add(tf.keras.layers.Dense(100, activation=tf.nn.relu))

model.add(tf.keras.layers.Dense(150, activation=tf.nn.relu))

model.add(tf.keras.layers.Dense(60, activation=tf.nn.relu))

model.add(tf.keras.layers.Dense(4, activation=tf.nn.softmax))

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

NameError: name 'model' is not defined

In [172]:
from sklearn.cross_validation import train_test_split
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size = 0.25, random_state = 42)

In [201]:
model.fit(Xtrain.values, ytrain.values, epochs=1500,batch_size=8)

Epoch 1/1500
1500/1500 [==============================] - 1s 930us/step - loss: 12.0670 - acc: 0.2500
Epoch 2/1500
1500/1500 [==============================] - 1s 420us/step - loss: 12.1638 - acc: 0.2453
Epoch 3/1500
1500/1500 [==============================] - 1s 422us/step - loss: 12.1638 - acc: 0.2453
Epoch 4/1500
1500/1500 [==============================] - 1s 402us/step - loss: 12.1638 - acc: 0.2453
Epoch 5/1500
1500/1500 [==============================] - 1s 399us/step - loss: 12.1638 - acc: 0.2453
Epoch 6/1500
1500/1500 [==============================] - 1s 406us/step - loss: 12.1638 - acc: 0.2453
Epoch 7/1500
1500/1500 [==============================] - 1s 414us/step - loss: 12.1638 - acc: 0.2453
Epoch 8/1500
1500/1500 [==============================] - 1s 396us/step - loss: 12.1638 - acc: 0.2453
Epoch 9/1500
1500/1500 [==============================] - 1s 418us/step - loss: 12.1638 - acc: 0.2453
Epoch 10/1500
1500/1500 [==============================] - 1s 418us/step - loss: 1

KeyboardInterrupt: 

In [151]:
classifier.fit(Xtrain,ytrain)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [198]:
from sklearn.metrics import confusion_matrix

In [199]:
max_acc = 0
max_rs = 0
for i in range(1001):
    Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size = 0.25, random_state = i)
    classifier.fit(Xtrain, ytrain)
    pred = classifier.predict(Xtest)
    cm = confusion_matrix(ytest, pred)
    print(cm, end = '\n\n')
    accuracy = (cm[0][0]+cm[1][1]+cm[2][2]+cm[3][3])/500
    print(i, accuracy, sep='==>')
    if(accuracy>max_acc):
        max_acc = accuracy
        max_rs = i
    if(i%100 == 0):
        print('Max accuracy till now is: ' + str(max_acc))

[[104  20   0   0]
 [ 29  65  14   2]
 [  4  38  65  18]
 [  0   8  43  90]]

0==>0.648
Max accuracy till now is: 0.648
[[86 30  0  0]
 [45 63 17  1]
 [ 2 49 68 16]
 [ 1  5 30 87]]

1==>0.608
[[101  21   0   0]
 [ 44  73  16   0]
 [  3  41  63  12]
 [  0   2  27  97]]

2==>0.668
[[98 22  0  0]
 [39 73 20  0]
 [ 4 37 61 15]
 [ 0  4 39 88]]

3==>0.64
[[106  23   0   0]
 [ 40  70  18   1]
 [  2  31  63  17]
 [  0   5  36  88]]

4==>0.654
[[111  18   0   0]
 [ 40  56  22   0]
 [  4  45  66  14]
 [  0   4  29  91]]

5==>0.648
[[103  19   0   0]
 [ 44  72  19   1]
 [  2  41  62  18]
 [  0   9  38  72]]

6==>0.618
[[101  35   0   0]
 [ 22  63  24   1]
 [  0  48  68  15]
 [  0   1  35  87]]

7==>0.638
[[101  22   0   0]
 [ 39  65  20   2]
 [  4  39  66  16]
 [  0   4  31  91]]

8==>0.646
[[102  27   1   0]
 [ 39  65  17   0]
 [  4  42  60  18]
 [  1   3  32  89]]

9==>0.632
[[91 26  1  0]
 [42 64 20  0]
 [ 2 42 77 13]
 [ 0  1 38 83]]

10==>0.63
[[103  18   0   0]
 [ 39  67  17   2]
 [  1  44  

KeyboardInterrupt: 

In [210]:
max_acc,max_rs

(0.958, 455)

In [174]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size = 0.25, random_state = 455)
classifier.fit(Xtrain, ytrain)
pred = classifier.predict(Xtest)
cm = confusion_matrix(ytest, pred)
print(cm, end = '\n\n')
accuracy = (cm[0][0]+cm[1][1]+cm[2][2]+cm[3][3])/500
print(accuracy, sep='==>')

[[141   1   0   0]
 [  3 116   3   0]
 [  0   3 110   3]
 [  0   0   8 112]]

0.958


In [175]:
cm

array([[141,   1,   0,   0],
       [  3, 116,   3,   0],
       [  0,   3, 110,   3],
       [  0,   0,   8, 112]], dtype=int64)

In [176]:
pred = classifier.predict(df2)

In [177]:
pred

array([3., 3., 3., 3., 1., 3., 3., 1., 3., 0., 3., 3., 0., 0., 2., 0., 2.,
       1., 3., 2., 1., 3., 1., 1., 3., 0., 2., 0., 3., 0., 2., 0., 3., 0.,
       0., 1., 3., 1., 2., 1., 1., 2., 0., 0., 0., 1., 0., 3., 1., 2., 1.,
       0., 2., 0., 3., 1., 3., 1., 1., 3., 3., 2., 0., 2., 1., 1., 1., 3.,
       1., 2., 1., 2., 2., 3., 3., 0., 2., 0., 2., 3., 0., 3., 3., 0., 3.,
       0., 3., 1., 2., 0., 1., 2., 2., 1., 2., 2., 0., 2., 1., 2., 1., 0.,
       0., 3., 0., 2., 0., 1., 2., 3., 3., 3., 1., 3., 3., 3., 3., 2., 3.,
       0., 0., 3., 2., 1., 2., 0., 3., 2., 3., 1., 0., 2., 1., 1., 3., 1.,
       1., 0., 3., 2., 1., 3., 1., 2., 2., 3., 3., 3., 2., 3., 2., 3., 1.,
       0., 3., 2., 3., 3., 3., 3., 2., 2., 3., 3., 3., 3., 1., 0., 3., 0.,
       0., 0., 2., 1., 0., 1., 0., 0., 1., 2., 1., 0., 0., 1., 1., 2., 2.,
       1., 0., 0., 0., 1., 0., 3., 1., 0., 2., 2., 3., 3., 1., 2., 2., 2.,
       3., 2., 2., 1., 0., 0., 1., 2., 0., 3., 3., 3., 0., 2., 0., 3., 2.,
       3., 3., 1., 0., 1.

In [178]:
data = pd.DataFrame({'price_range':pred[:]})
pd.DataFrame.to_csv(data, path_or_buf='Onehotencoded.csv', encoding='utf-8')

In [516]:
df.head()

1    2    3    4    5    6    7    8    9    10  ...   314  315  316  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  1.0  1.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0 ...   1.0  1.0  1.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0 ...   1.0  0.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.0  0.0  1.0   

      317     318     319  320  321  322  323  
0    20.0   756.0  2549.0  0.0  0.0  1.0  1.0  
1   905.0  1988.0  2631.0  1.0  1.0  0.0  2.0  
2  1263.0  1716.0  2603.0  1.0  1.0  0.0  2.0  
3  1216.0  1786.0  2769.0  1.0  0.0  0.0  2.0  
4  1208.0  1212.0  1411.0  1.0  1.0  0.0  1.0  

[5 rows x 323 columns]

In [195]:
from sklearn.preprocessing import StandardScaler

In [196]:
sc = StandardScaler()

In [197]:
X.iloc[:,[312,316,317,318]] = sc.fit_transform(X.iloc[:,[312,316,317,318]])

C:\Anaconda\lib\site-packages\pandas\core\indexing.py:189: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
C:\Anaconda\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [98]:
X.head()

1    2    3    4    5    6    7    8    9    10  ...        313  314  315  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...  -0.902597  0.0  0.0   
1  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0 ...  -0.495139  1.0  1.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0 ...  -1.537686  1.0  1.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0 ...  -1.419319  1.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   1.325906  1.0  0.0   

   316       317       318       319  320  321  322  
0  0.0 -1.408949 -1.146784  0.391703  0.0  0.0  1.0  
1  1.0  0.585778  1.704465  0.467317  1.0  1.0  0.0  
2  1.0  1.392684  1.074968  0.441498  1.0  1.0  0.0  
3  0.0  1.286750  1.236971  0.594569  1.0  0.0  0.0  
4  1.0  1.268718 -0.091452 -0.657666  1.0  1.0  0.0  

[5 rows x 322 columns]

In [379]:
max_acc = 0
max_rs = 0
for i in range(1001):
    Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size = 0.25, random_state = i)
    classifier.fit(Xtrain, ytrain)
    pred = classifier.predict(Xtest)
    cm = confusion_matrix(ytest, pred)
    print(cm, end = '\n\n')
    accuracy = (cm[0][0]+cm[1][1]+cm[2][2]+cm[3][3])/500
    print(i, accuracy, sep='==>')
    if(accuracy>max_acc):
        max_acc = accuracy
        max_rs = i
    if(i%100 == 0):
        print('Max accuracy till now is: ' + str(max_acc))

C:\Anaconda\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[122   2   0   0]
 [  7  94   9   0]
 [  0   9 108   8]
 [  0   0   9 132]]

0==>0.912
Max accuracy till now is: 0.912


C:\Anaconda\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[109   7   0   0]
 [  4 109  13   0]
 [  0  17 109   9]
 [  0   0  11 112]]

1==>0.878


C:\Anaconda\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[118   4   0   0]
 [ 11 117   5   0]
 [  0   7 107   5]
 [  0   0   7 119]]

2==>0.922


C:\Anaconda\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[117   3   0   0]
 [  4 118  10   0]
 [  0  10 102   5]
 [  0   0   9 122]]

3==>0.918


C:\Anaconda\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[124   5   0   0]
 [  3 115  11   0]
 [  0   6 102   5]
 [  0   0   8 121]]

4==>0.924


C:\Anaconda\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[122   7   0   0]
 [ 10 102   6   0]
 [  0  11 114   4]
 [  0   0   9 115]]

5==>0.906


C:\Anaconda\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[119   3   0   0]
 [  7 118  11   0]
 [  0  13 104   6]
 [  0   0  11 108]]

6==>0.898


C:\Anaconda\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[129   7   0   0]
 [  5  99   6   0]
 [  0  11 111   9]
 [  0   0  11 112]]

7==>0.902


C:\Anaconda\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[120   3   0   0]
 [  7 114   5   0]
 [  0  15 105   5]
 [  0   0   7 119]]

8==>0.916


C:\Anaconda\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[123   7   0   0]
 [ 11 105   5   0]
 [  0  14 106   4]
 [  0   0  11 114]]

9==>0.896


C:\Anaconda\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[113   5   0   0]
 [  9 115   2   0]
 [  0  13 108  13]
 [  0   0   6 116]]

10==>0.904


C:\Anaconda\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[116   5   0   0]
 [  9 105  11   0]
 [  0  13 102   6]
 [  0   0   9 124]]

11==>0.894


C:\Anaconda\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[122   7   0   0]
 [  7 110  14   0]
 [  0   4 107   6]
 [  0   0   7 116]]

12==>0.91


C:\Anaconda\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[120   5   0   0]
 [ 11 109   4   0]
 [  0   9 106   6]
 [  0   0  13 117]]

13==>0.904


C:\Anaconda\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[113   6   0   0]
 [  7  98  10   0]
 [  0  15 118   4]
 [  0   0   7 122]]

14==>0.902


C:\Anaconda\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[107   4   0   0]
 [  7 124   8   0]
 [  0  11  99   9]
 [  0   0   7 124]]

15==>0.908


C:\Anaconda\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[109  10   0   0]
 [  6 105   7   0]
 [  0  15 115   5]
 [  0   0   7 121]]

16==>0.9


C:\Anaconda\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


[[118   5   0   0]
 [  5 111  10   0]
 [  0   8 108  10]
 [  0   0   7 118]]

17==>0.91
[[120   6   0   0]
 [  7 116   8   0]
 [  0   8 113  11]
 [  0   0  11 100]]

18==>0.898


C:\Anaconda\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


KeyboardInterrupt: 

In [386]:
X.iloc[1481]

1      0.000000
2      0.000000
3      0.000000
4      0.000000
5      0.000000
6      0.000000
7      0.000000
8      0.000000
9      0.000000
10     0.000000
11     0.000000
12     0.000000
13     0.000000
14     1.000000
15     0.000000
16     0.000000
17     0.000000
18     0.000000
19     0.000000
20     0.000000
21     0.000000
22     0.000000
23     0.000000
24     0.000000
25     0.000000
26     0.000000
27     0.000000
28     0.000000
29     0.000000
30     0.000000
         ...   
293    0.000000
294    0.000000
295    0.000000
296    0.000000
297    0.000000
298    0.000000
299    0.000000
300    0.000000
301    0.000000
302    0.000000
303    1.000000
304    0.000000
305    0.000000
306    0.000000
307    0.000000
308    0.000000
309    0.000000
310    0.000000
311    0.000000
312    0.000000
313    1.355498
314    0.000000
315    0.000000
316    1.000000
317   -1.454027
318    1.702150
319    1.445683
320    1.000000
321    1.000000
322    0.000000
Name: 1481, Length: 322,

In [91]:
# applying the deep learning layers
import keras
from keras.layers import Dense
from keras.models import Sequential
from keras.layers import Dropout

C:\Anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [92]:
y = y.values
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features = [0],handle_unknown='ignore')
y = onehotencoder.fit_transform(y.reshape(-1, 1)).toarray()

In [93]:
'''splitting up the dataset'''
from sklearn.model_selection import train_test_split
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size = 0.25, random_state = 434)

In [94]:
''' making the object'''
# initialising the sequential
classifier = Sequential()

In [95]:
# adding the 1st layer and the hidden layer
classifier.add(Dense(100, input_dim = 322, activation = 'relu', kernel_initializer='glorot_uniform'))
classifier.add(Dropout(rate = 0.1))

In [96]:
# adding the first layer
classifier.add(Dense(100, kernel_initializer='glorot_uniform', activation = 'relu'))
classifier.add(Dropout(rate = 0.1))

In [97]:
# adding the second layer
classifier.add(Dense(100, kernel_initializer = 'glorot_uniform', activation = 'relu'))
classifier.add(Dropout(rate = 0.1))

In [98]:
classifier.add(Dense(100, kernel_initializer = 'glorot_uniform', activation = 'relu'))
classifier.add(Dropout(rate = 0.1))

In [99]:
classifier.add(Dense(100, kernel_initializer = 'glorot_uniform', activation = 'relu'))
classifier.add(Dropout(rate = 0.1))

In [100]:
# adding the final layer
classifier.add(Dense(4, kernel_initializer = 'glorot_uniform', activation = 'softmax'))

In [101]:
# compliling the results
classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [102]:
# fitting the model
classifier.fit(Xtrain, ytrain, batch_size = 8,  epochs = 250)
print('***************************************************\n**********************************************')

Epoch 1/250
1500/1500 [==============================] - 1s 642us/step - loss: 11.9812 - acc: 0.2567
Epoch 2/250
1500/1500 [==============================] - 0s 289us/step - loss: 12.0026 - acc: 0.2553
Epoch 3/250
1500/1500 [==============================] - 0s 293us/step - loss: 12.0026 - acc: 0.2553
Epoch 4/250
1500/1500 [==============================] - 0s 299us/step - loss: 12.0026 - acc: 0.2553
Epoch 5/250
1500/1500 [==============================] - 0s 305us/step - loss: 12.0026 - acc: 0.2553
Epoch 6/250
1500/1500 [==============================] - 0s 281us/step - loss: 12.0026 - acc: 0.2553
Epoch 7/250
1500/1500 [==============================] - 0s 296us/step - loss: 12.0026 - acc: 0.2553
Epoch 8/250
1500/1500 [==============================] - 0s 283us/step - loss: 12.0026 - acc: 0.2553
Epoch 9/250
1500/1500 [==============================] - 0s 293us/step - loss: 12.0026 - acc: 0.2553
Epoch 10/250
1500/1500 [==============================] - 0s 297us/step - loss: 12.0026 - a

KeyboardInterrupt: 

In [111]:
y_pred = classifier.predict_classes(Xtest)

In [112]:
y_pred_df = pd.DataFrame(y_pred)
y_pred_df.head(10)

0
0  3
1  2
2  0
3  1
4  2
5  0
6  3
7  1
8  0
9  2

In [113]:
classifier.test_on_batch(Xtest, ytest)

[1.5128964, 0.814]

In [114]:
ytest[480:]

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [115]:
y_pred[480:]

array([3, 2, 0, 0, 3, 3, 3, 3, 1, 3, 2, 0, 3, 0, 2, 2, 1, 0, 0, 0],
      dtype=int64)

In [545]:
def inverse_transform(self, X):
        """Convert the back data to the original representation.
        In case unknown categories are encountered (all zero's in the
        one-hot encoding), ``None`` is used to represent this category.
        Parameters
        ----------
        X : array-like or sparse matrix, shape [n_samples, n_encoded_features]
            The transformed data.
        Returns
        -------
        X_tr : array-like, shape [n_samples, n_features]
            Inverse transformed array.
        """
        # if self._legacy_mode:
        #     raise ValueError("only supported for categorical features")

        check_is_fitted(self, 'categories_')
        X = check_array(X, accept_sparse='csr')

        n_samples, _ = X.shape
        n_features = len(self.categories_)
        n_transformed_features = sum([len(cats) for cats in self.categories_])

        # validate shape of passed X
        msg = ("Shape of the passed X data is not correct. Expected {0} "
               "columns, got {1}.")
        if X.shape[1] != n_transformed_features:
            raise ValueError(msg.format(n_transformed_features, X.shape[1]))

        # create resulting array of appropriate dtype
        dt = np.find_common_type([cat.dtype for cat in self.categories_], [])
        X_tr = np.empty((n_samples, n_features), dtype=dt)

        j = 0
        found_unknown = {}

        for i in range(n_features):
            n_categories = len(self.categories_[i])
            sub = X[:, j:j + n_categories]

            # for sparse X argmax returns 2D matrix, ensure 1D array
            labels = np.asarray(_argmax(sub, axis=1)).flatten()
            X_tr[:, i] = self.categories_[i][labels]

            if self.handle_unknown == 'ignore':
                # ignored unknown categories: we have a row of all zero's
                unknown = np.asarray(sub.sum(axis=1) == 0).flatten()
                if unknown.any():
                    found_unknown[i] = unknown

            j += n_categories

        # if ignored are found: potentially need to upcast result to
        # insert None values
        if found_unknown:
            if X_tr.dtype != object:
                X_tr = X_tr.astype(object)

            for idx, mask in found_unknown.items():
                X_tr[mask, idx] = None

        return X_tr

In [556]:
len(ytest[0])

4

In [578]:
test = []
for i in range(len(ytest)):
    for j in range(len(ytest[i])):
        if ytest[i][j] == 1:
            test.append(j)
            break

In [579]:
test

[0,
 2,
 1,
 3,
 1,
 1,
 2,
 0,
 3,
 1,
 0,
 0,
 2,
 3,
 3,
 2,
 3,
 3,
 1,
 0,
 0,
 2,
 1,
 2,
 0,
 1,
 3,
 2,
 2,
 0,
 0,
 0,
 3,
 0,
 1,
 1,
 2,
 0,
 3,
 0,
 2,
 3,
 2,
 0,
 2,
 3,
 2,
 1,
 3,
 1,
 3,
 1,
 0,
 0,
 1,
 0,
 1,
 3,
 0,
 0,
 1,
 3,
 3,
 1,
 0,
 0,
 3,
 3,
 1,
 2,
 2,
 2,
 0,
 1,
 2,
 0,
 1,
 3,
 2,
 2,
 3,
 2,
 1,
 0,
 1,
 3,
 1,
 3,
 3,
 0,
 3,
 3,
 2,
 1,
 3,
 2,
 2,
 3,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 3,
 2,
 0,
 1,
 1,
 0,
 0,
 3,
 1,
 3,
 2,
 3,
 2,
 0,
 2,
 1,
 3,
 2,
 1,
 3,
 3,
 0,
 2,
 0,
 2,
 3,
 0,
 2,
 2,
 0,
 3,
 1,
 0,
 0,
 2,
 2,
 1,
 3,
 2,
 0,
 0,
 0,
 1,
 1,
 2,
 3,
 1,
 1,
 0,
 2,
 2,
 0,
 1,
 0,
 2,
 2,
 3,
 3,
 2,
 1,
 0,
 1,
 2,
 2,
 3,
 3,
 0,
 1,
 0,
 3,
 1,
 1,
 2,
 1,
 0,
 0,
 0,
 0,
 0,
 3,
 2,
 0,
 3,
 0,
 0,
 0,
 0,
 1,
 3,
 3,
 1,
 0,
 1,
 1,
 1,
 1,
 2,
 2,
 3,
 3,
 3,
 1,
 2,
 0,
 0,
 0,
 2,
 1,
 1,
 3,
 1,
 0,
 2,
 1,
 1,
 3,
 2,
 3,
 0,
 0,
 2,
 1,
 3,
 0,
 1,
 2,
 0,
 2,
 3,
 2,
 0,
 1,
 3,
 3,
 0,
 1,
 3,
 2,
 3,
 0,
 3,
 1,
 2,
 3,
 3,


In [582]:
confusion_matrix(test,y_pred)

array([[121,  11,   0,   0],
       [ 14,  98,   6,   0],
       [  0,  18,  87,  15],
       [  0,   0,  13, 117]], dtype=int64)

In [202]:
ytest

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       ...,
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.]])